//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public int ExpenseID { get; set; }
        public Nullable<System.DateTime> ExpenseDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Description { get; set; }
        public Nullable<int> ExpenseTypeID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SalaryID { get; set; }
        public Nullable<int> SalaryCurrenciesId { get; set; }
    
        public virtual CurrencyTypes CurrencyTypes { get; set; }
        public virtual ExpenseTypes ExpenseTypes { get; set; }
        public virtual Salaries Salaries { get; set; }
    }
}
